# @package _global_

defaults:
  - override /data: libero_2cam
  - override /model: fastwam
  - _self_

# dataloading
# 如果设置过大容易导致 Libero 训练时 GPU OOM
batch_size: 16

# 如果设置过大容易导致 Libero 训练时 CPU OOM
num_workers: 2

model:
  mot_checkpoint_mixed_attn: false

# scheduler
lr_scheduler_type: "cosine"
learning_rate: 1e-4
num_epochs: 10
# max_steps: null
max_steps: 20000
log_every: 10
save_every: 2000
eval_every: 200

# training
gradient_accumulation_steps: 1
weight_decay: 1e-2
resume: null
